# Generated by Django 4.2.1 on 2023-06-15 10:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='courses',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
